# Generated by Django 5.1 on 2024-10-24 14:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=2048)),
                ('collection', models.CharField(blank=True, default='', max_length=256)),
                ('provider', models.CharField(blank=True, default='', max_length=256)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('sensor_type', models.CharField(blank=True, default='', max_length=256)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=2048)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
