# Generated by Django 5.1 on 2024-10-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('augury', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveitem',
            name='metadata',
            field=models.CharField(blank=True, default='', max_length=4096),
        ),
    ]
