# Generated by Django 5.1 on 2024-11-06 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0010_archiveitem_remove_archiveresult_archive_lookup_and_more'),
        ('augury', '0002_archiveitem_metadata'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('study_id', models.PositiveIntegerField()),
                ('status', models.CharField(blank=True, choices=[('INITIALIZED', 'Initialized'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PROCESSING', 'Processing'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed'), ('ANOMALOUS', 'Anomalous')], default='INITIALIZED', max_length=128)),
                ('study_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='ArchiveItem',
        ),
        migrations.AddIndex(
            model_name='dream',
            index=models.Index(fields=['study_type', 'study_id'], name='augury_drea_study_t_3191b5_idx'),
        ),
    ]
