FROM python:3.11-slim

WORKDIR /augur
RUN apt-get update \
  && apt-get install -y \
         vim \
         gdal-bin \
  && apt-get clean

RUN useradd -ms /bin/bash augur
COPY . /augur
RUN pip install --upgrade pip pip-tools
RUN pip-compile --output-file=requirements.txt pyproject.toml
RUN pip-sync
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
