# Generated by Django 5.1 on 2024-09-03 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_integrationconfigoption_key'),
        ('provider', '0002_delete_configoption_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('INITIALIZED', 'Initialized'), ('SEEKING', 'Seeking'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='INITIALIZED', max_length=128)),
                ('rules', models.CharField(blank=True, default='', max_length=65536)),
                ('imagery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.imageryrequest')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArchiveResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('rules', models.CharField(blank=True, default='', max_length=65536)),
                ('metadata', models.CharField(blank=True, default='', max_length=65536)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=2048)),
                ('product_type', models.CharField(blank=True, default='', max_length=256)),
                ('archive_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.archivefinder')),
                ('provider_integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.providerintegration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
