# Generated by Django 5.1 on 2024-09-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0001_initial'),
        ('provider', '0003_providerintegration_capability_options_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('archive_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.archiveresult')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
