# Generated by Django 5.1 on 2024-10-05 23:30

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0003_remove_archivefinder_imagery_request_and_more'),
        ('core', '0006_sensortype_alter_user_organization'),
        ('provider', '0003_providerintegration_capability_options_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveresult',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='archiveresult',
            name='provider_integration',
        ),
        migrations.RemoveField(
            model_name='archiveresult',
            name='rules',
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(default=None, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='provider.provider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='seeker_run_id',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='sensor_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.sensortype'),
            preserve_default=False,
        ),
    ]
