# Generated by Django 5.1 on 2024-10-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0004_remove_archiveresult_product_type_and_more'),
        ('provider', '0004_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archiveresult',
            name='provider',
        ),
        migrations.AddField(
            model_name='archiveresult',
            name='collection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='provider.collection'),
            preserve_default=False,
        ),
    ]
