# Generated by Django 5.1 on 2024-10-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0005_remove_archiveresult_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archiveresult',
            name='thumbnail',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
