# Generated by Django 5.1 on 2024-11-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0008_remove_archiveresult_archive_finder_archivelookup_and_more'),
        ('augury', '0002_archiveitem_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivelookup',
            name='archive_items',
        ),
        migrations.AddField(
            model_name='archivelookup',
            name='archive_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='augury.archiveitem'),
        ),
    ]
