# Generated by Django 5.1 on 2024-11-06 18:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0009_remove_archivelookup_archive_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=2048)),
                ('collection', models.CharField(blank=True, default='', max_length=256)),
                ('provider', models.CharField(blank=True, default='', max_length=256)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('sensor', models.CharField(blank=True, default='', max_length=256)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=2048)),
                ('metadata', models.CharField(blank=True, default='', max_length=4096)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='archiveresult',
            name='archive_lookup',
        ),
        migrations.RemoveField(
            model_name='archiveorder',
            name='archive_result',
        ),
        migrations.RemoveField(
            model_name='archiveorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='archiveresult',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='archiveresult',
            name='sensor_type',
        ),
        migrations.RemoveField(
            model_name='archivefinder',
            name='status',
        ),
        migrations.DeleteModel(
            name='ArchiveLookup',
        ),
        migrations.DeleteModel(
            name='ArchiveOrder',
        ),
        migrations.DeleteModel(
            name='ArchiveResult',
        ),
    ]
