# Generated by Django 5.1 on 2024-11-07 22:57

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0010_archiveitem_remove_archiveresult_archive_lookup_and_more'),
        ('core', '0009_sensor_delete_sensortype'),
        ('provider', '0004_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageryLookupStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('archive_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.archivefinder')),
                ('archive_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_finder.archiveitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageryLookupResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('external_id', models.CharField(blank=True, default='', max_length=2048)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=2048)),
                ('metadata', models.CharField(blank=True, default='', max_length=65536)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.collection')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensor')),
                ('imagery_lookup_study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_finder.imagerylookupstudy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
