# Generated by Django 5.1 on 2024-11-08 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0011_imagerylookupstudy_imagerylookupresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerylookupresult',
            name='imagery_lookup_study',
        ),
        migrations.RemoveField(
            model_name='imagerylookupstudy',
            name='archive_item',
        ),
        migrations.AddField(
            model_name='imagerylookupresult',
            name='study',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='archive_finder.imagerylookupstudy'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ImageryLookupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('archive_finder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.archivefinder')),
                ('archive_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive_finder.archiveitem')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive_finder.imagerylookupstudy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
