# Generated by Django 5.1 on 2024-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_integrationconfigoption_internalintegration'),
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigOption',
        ),
        migrations.AlterField(
            model_name='providerintegration',
            name='config_options',
            field=models.ManyToManyField(to='core.integrationconfigoption'),
        ),
    ]
