# Generated by Django 5.1 on 2024-10-06 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_providerintegration_capability_options_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=512)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.provider')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
