# Generated by Django 5.1 on 2024-09-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfigOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('key', models.CharField(choices=[('username', 'Username'), ('password', 'Password'), ('api_key', 'Api Key'), ('client_id', 'Client Id'), ('client_secret', 'Client Secret'), ('token_refresh_endpoint', 'Token Refresh Endpoint'), ('auth_endpoint', 'Auth Endpoint'), ('task_endpoint', 'Task Endpoint'), ('collect_endpoint', 'Collect Endpoint'), ('stac_endpoint', 'Stac Endpoint')], max_length=512)),
                ('value', models.CharField(max_length=4096)),
                ('is_secret', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InternalIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('config_options', models.ManyToManyField(to='core.integrationconfigoption')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
