# Generated by Django 5.1 on 2024-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_integrationconfigoption_internalintegration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconfigoption',
            name='key',
            field=models.CharField(choices=[('username', 'Username'), ('password', 'Password'), ('api_key', 'Api Key'), ('client_id', 'Client Id'), ('client_secret', 'Client Secret'), ('token_refresh_endpoint', 'Token Refresh Endpoint'), ('auth_endpoint', 'Auth Endpoint'), ('task_endpoint', 'Task Endpoint'), ('collect_endpoint', 'Collect Endpoint'), ('stac_endpoint', 'Stac Endpoint'), ('generic_endpoint', 'Generic Endpoint')], max_length=512),
        ),
    ]
