# Generated by Django 5.1 on 2024-09-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_integrationconfigoption_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCapabilityOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('value', models.CharField(choices=[('archive_search', 'Archive Search'), ('archive_download', 'Archive Download'), ('archive_pricing', 'Archive Pricing'), ('archive_order', 'Archive Order'), ('feasibility_search', 'Feasibility Search'), ('tasking_search', 'Tasking Search'), ('tasking_pricing', 'Tasking Pricing'), ('tasking_order', 'Tasking Order'), ('tasking_order_status', 'Tasking Order Status'), ('tasking_download', 'Tasking Download'), ('tasking_download_status', 'Tasking Download Status')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
