# Generated by Django 5.1 on 2024-10-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_integrationcapabilityoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalintegration',
            name='capability_options',
            field=models.ManyToManyField(to='core.integrationcapabilityoption'),
        ),
    ]
