# Generated by Django 5.1 on 2024-10-05 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sensortype_alter_user_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensortype',
            name='sensor',
        ),
        migrations.AddField(
            model_name='sensortype',
            name='technique',
            field=models.CharField(choices=[('SAR', 'Sar'), ('EO', 'Eo'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=128),
        ),
    ]
