# Generated by Django 5.1 on 2024-10-06 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_sensortype_sensor_sensortype_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortype',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensortype',
            name='modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
