# Generated by Django 5.1 on 2024-11-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive_finder', '0010_archiveitem_remove_archiveresult_archive_lookup_and_more'),
        ('core', '0008_sensortype_created_sensortype_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('technique', models.CharField(choices=[('SAR', 'Sar'), ('EO', 'Eo'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=128)),
                ('name', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='SensorType',
        ),
    ]
