"""
Django settings for augur project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

def parse_env_bool(val):
    return str(val) == "True"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('AUGUR_SECRET_KEY', 'not-secret-key-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx') 

SECURE_SSL_REDIRECT = parse_env_bool(os.environ.get('AUGUR_SECURE_SSL_REDIRECT', True))
if SECURE_SSL_REDIRECT:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = parse_env_bool(os.environ.get('AUGUR_DEBUG', False))

ALLOWED_HOSTS = os.environ.get('AUGUR_ALLOWED_HOSTS', '').split(',')
SESSION_COOKIE_SECURE = parse_env_bool(os.environ.get('AUGUR_SESSION_COOKIE_SECURE', True))
CSRF_COOKIE_SECURE = parse_env_bool(os.environ.get('AUGUR_CSRF_COOKIE_SECURE', True))

DREAMFLOW_HOST = os.environ.get('AUGUR_DREAMFLOW_HOST', '')
DREAMFLOW_USER = os.environ.get('AUGUR_DREAMFLOW_USER', '')
DREAMFLOW_PASSWORD = os.environ.get('AUGUR_DREAMFLOW_PASSWORD', '')

CORS_ALLOWED_ORIGINS = os.environ.get('AUGUR_CORS_ALLOWED_ORIGINS', '').split(',')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django_extensions',
    'corsheaders',
    'core.apps.CoreConfig',
    'provider.apps.ProviderConfig',
    'augury.apps.AuguryConfig',
    'feasibility_finder.apps.FeasibilityFinderConfig',
    'archive_finder.apps.ArchiveFinderConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'augur.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'augur.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.environ.get("AUGUR_DB_NAME", "augur"),
        "USER": os.environ.get("AUGUR_DB_USER", "postgres"),
        "PASSWORD": os.environ.get("AUGUR_DB_PASSWORD", "postgres"),
        "HOST": os.environ.get("AUGUR_DB_HOST", "atlas"),
        "PORT": os.environ.get("AUGUR_DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Use our User model
AUTH_USER_MODEL = 'core.User'
