# Generated by Django 5.1 on 2024-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_finder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feasibilityresult',
            name='confidence_score',
        ),
        migrations.AddField(
            model_name='feasibilityfinder',
            name='rules',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
        migrations.AddField(
            model_name='feasibilityfinder',
            name='status',
            field=models.CharField(blank=True, choices=[('INITIALIZED', 'Initialized'), ('SEEKING', 'Seeking'), ('RESTING', 'Resting'), ('FAILED', 'Failed')], default='INITIALIZED', max_length=128),
        ),
        migrations.AddField(
            model_name='feasibilityresult',
            name='feasibility_data',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
    ]
