# Generated by Django 5.1 on 2024-09-02 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_finder', '0002_remove_feasibilityresult_confidence_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feasibilityresult',
            old_name='feasibility_data',
            new_name='metadata',
        ),
        migrations.AddField(
            model_name='feasibilityresult',
            name='confidence_score',
            field=models.FloatField(blank=True, default=-1.0),
        ),
        migrations.AddField(
            model_name='feasibilityresult',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feasibilityresult',
            name='rules',
            field=models.CharField(blank=True, default='', max_length=65536),
        ),
        migrations.AddField(
            model_name='feasibilityresult',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
