# Generated by Django 5.1 on 2024-09-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_finder', '0003_rename_feasibility_data_feasibilityresult_metadata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feasibilityfinder',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
