# Generated by Django 5.1 on 2024-09-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_finder', '0004_alter_feasibilityfinder_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feasibilityresult',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=2048),
        ),
    ]
