# Generated by Django 5.1 on 2024-09-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_finder', '0005_feasibilityresult_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feasibilityfinder',
            name='status',
            field=models.CharField(blank=True, choices=[('INITIALIZED', 'Initialized'), ('SEEKING', 'Seeking'), ('FINISHED', 'Finished'), ('FAILED', 'Failed')], default='INITIALIZED', max_length=128),
        ),
    ]
