# Generated by Django 5.1 on 2024-09-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feasibility_finder', '0006_alter_feasibilityfinder_status'),
        ('provider', '0003_providerintegration_capability_options_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeasibilityOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('metadata', models.CharField(blank=True, default='', max_length=65536)),
                ('feasibility_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feasibility_finder.feasibilityresult')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
